### PR TITLE
[PROPOSED] Use exact dependencies version

### PR DESCRIPTION
**Pull request by cimasim89**
I propose to use exact dependencies version because I think is better for maintaining the project coherent during development and chose when changing the version.

### CODE REVIEW

**Comment by dottorblaster** [comment]
I'd love to merge this but I'm afraid Dependabot will stop working :D I have to dig a little bit to investigate

**Comment by cimasim89** [comment]
If I'm not mistaken this configuration option `versioning-strategy: increase` should resolve it.

**Comment by cimasim89** [comment]
Check if `dependabot.yml` could be right, I propose two labels that dependabot can automatically add to him new pull-request, but they have to be added:
  - kind/DEPENDENCIES
  - status/CR-NEEDED

**Review by dottorblaster — APPROVED** [review]
You convinced me. :smile: 

Let's try! Please squash the fixups :smiley:

**Pull request merged**
